from tkinter  import *
root =Tk()
root.geometry("500x700")
root.title("CALCULATOR by Hatim")
def click(click):
   global sv
   text=click.widget.cget("text")
   
   if text=="=":
      if sv.get().isdigit():
         value=int(sv.get())
      else:
         value=eval(sv.get())
      sv.set(value)
      screen.update()
      
   elif text=="c":
       sv.set("")
       screen.update()
   else:
      sv.set(sv.get()+text)
      screen.update()
   
   
sv=StringVar()
sv.set("")
screen=Entry(root,text=sv,font="500")
screen.pack(fill=X,ipadx=8,padx=10,pady=10)
f=Frame(root,background="grey")
b=Button(f,text="9",font=100,padx=22,pady=22)
b.pack(side="left",padx=22,pady=12)
b.bind("<Button-1>",click)
b=Button(f,text="8",font=100,padx=22,pady=22)
b.pack(side="left",padx=12,pady=12)
b.bind("<Button-1>",click)
b=Button(f,text="7",font=100,padx=22,pady=22)
b.pack(side="left",padx=12,pady=12)
b.bind("<Button-1>",click)
f.pack()
f=Frame(root,background="grey")
b=Button(f,text="6",font=100,padx=22,pady=22)
b.pack(side="left",padx=12,pady=12)
b.bind("<Button-1>",click)
b=Button(f,text="5",font=100,padx=22,pady=22)
b.pack(side="left",padx=12,pady=12)
b.bind("<Button-1>",click)
b=Button(f,text="4",font=100,padx=22,pady=22)
b.pack(side="left",padx=12,pady=12)
b.bind("<Button-1>",click)
f.pack()
f=Frame(root,background="grey")
b=Button(f,text="3",font=100,padx=22,pady=22)
b.pack(side="left",padx=12,pady=12)
b.bind("<Button-1>",click)
b=Button(f,text="2",font=100,padx=22,pady=22)
b.pack(side="left",padx=12,pady=12)
b.bind("<Button-1>",click)
b=Button(f,text="1",font=100,padx=22,pady=22)
b.pack(side="left",padx=12,pady=12)
b.bind("<Button-1>",click)
f.pack()
f=Frame(root,background="grey")
b=Button(f,text="+",font=100,padx=22,pady=22)
b.pack(side="left",padx=12,pady=12)
b.bind("<Button-1>",click)
b=Button(f,text="-",font=100,padx=22,pady=22)
b.pack(side="left",padx=12,pady=12)
b.bind("<Button-1>",click)
b=Button(f,text="*",font=100,padx=22,pady=22)
b.pack(side="left",padx=12,pady=12)
b.bind("<Button-1>",click)
f.pack()
f=Frame(root,background="grey")
b=Button(f,text="/",font=100,padx=22,pady=22)
b.pack(side="left",padx=12,pady=12)
b.bind("<Button-1>",click)
b=Button(f,text="c",font=100,padx=22,pady=22)
b.pack(side="left",padx=12,pady=12)
b.bind("<Button-1>",click)
b=Button(f,text="=",font=100,padx=22,pady=22)
b.pack(side="left",padx=12,pady=12)
b.bind("<Button-1>",click)
f.pack()
root.mainloop()